### ISSUE TITLE
Entry Point Not Found : The procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll

### ISSUE THREAD

**Issue by Deace** [crystalidea/qt6windows7#11]
Hello,

I created a Qt application compiled with Qt 6.6.0 and MSVC 2019 64-bit. Following the instructions, I replaced the related .dll files with the originals, including qwindows.dll. The application works fine on Windows 10, but on Windows 7, it encounters an issue:

"Entry Point Not Found: The procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll."

Thank you for any help or suggestions you can provide.

**Comment by kleuter** [comment]
1. You must compile your app against Qt 6.6.2
2. Make sure to replace Qt6Gui.dll
