### ISSUE TITLE
Zstandard support not compiled into pre-built binaries

### ISSUE THREAD

**Issue by snoopy-coder** [crystalidea/qt6windows7#19]
I came across this bug a couple of days ago:
[https://bugreports.qt.io/browse/QTBUG-127644](https://bugreports.qt.io/browse/QTBUG-127644)

Perhaps, it migrated here too:

![qt6_Zstd](https://github.com/user-attachments/assets/9e19b9fc-aa52-493f-9df7-3441b45caf01)

Is there any way to fix this? Thanks a lot.

**Comment by kleuter** [comment]
you should builds Qt 6.7.2 from source (with patches applied here) to enable zstd
