### ISSUE TITLE
qthread_win.cpp compiler error

### ISSUE THREAD

**Issue by adeii** [crystalidea/qt6windows7#25]
During  patched Qt 6.8.0 compiling with Strawberry Perl, as x86, error pop-up flied as:

_qthread_win.cpp:255:5: error: expected 'catch' before '__except_

I had overwrite file with previous Qt 6.5.3 version to continues. Hope it will work till the end.

**Comment by kleuter** [comment]
The error suggests you're likely compiling with a non-MSVC compiler, such as MinGW or GCC, which does not support SEH syntax like __try and __except.

**Comment by kleuter** [comment]
Should be fixed now
