### ISSUE TITLE
QT 6.5.3

### ISSUE THREAD

**Issue by LRGB** [crystalidea/qt6windows7#3]
Hi, I saw from the commit history that at some point you were maybe working on a 6.5.3 release but then jumped to 6.6.0. Any chance you could release that still? Its what the [new verion of Calibre is using](https://github.com/kovidgoyal/calibre/releases/tag/v7.0.0). I use the modified .dlls to keep it running on Windows 8.1.  Thanks!

**Comment by kleuter** [comment]
https://github.com/crystalidea/qt6windows7/releases/tag/6.5.3-win7

**Comment by LRGB** [comment]
Thanks,
 
Unfortunately it didn't work, I'm guessing they changed something else in the code that now makes it incompatible with W8.

**Comment by kleuter** [comment]
This DLLs are compiled with VC2019 and cannot be mixed with others compiled with different compiler.
Basically you need a complete set of DLLS as I just did for Qt 6.6, check it out:
https://github.com/crystalidea/qt6windows7/releases/tag/v6.6.0
